### ISSUE TITLE
shared links which show PDFs shows no pictures on OC 8.1

### ISSUE THREAD

**Issue by frompxkrat** [omigeot/owncloud-pdfviewer#2]
hello .. i posted this already here:
https://forum.owncloud.org/viewtopic.php?f=31&t=30751

on the end, i downloaded this repostory and pushed it online .. but the problem is still unsolved

see here .. it's ok with firefox:
in oc 8.04 it shows a shared link correctly .. a PDF with pictures inside:
http://www.technobau.ch/cloud/index.php/s/bbEzLi4N8vj6hPR

or here .. pictures missing with firefox:
in oc 8.1.3 it shows the same type of PDF's without pictures! 
http://tvbusch.ch/oase/index.php/s/E9DvxF7qHn9Cw4c

i tried it on different installations

what elese

**Comment by ghost** [comment]
@frompxkrat You can close this here with the button below as you had reported this at https://github.com/owncloud/files_pdfviewer/issues/69
